// Generated by Tools/src/generate-capability-catalog.mjs. Do not edit manually.
#pragma once

#include "CoreMinimal.h"

inline constexpr uint32 RmlUiCapabilitySchemaVersion = 1u;
inline constexpr uint32 RmlUiMinimumHostAbi = 2u;
inline constexpr uint32 RmlUiMinimumSlateAbi = 5u;

inline bool RmlUiKnownFeature(const FString& Feature)
{
    return Feature == TEXT("css.core") ||
        Feature == TEXT("css.grid") ||
        Feature == TEXT("css.motion") ||
        Feature == TEXT("css.variables") ||
        Feature == TEXT("events.extended") ||
        Feature == TEXT("input.ime") ||
        Feature == TEXT("layout.measure") ||
        Feature == TEXT("nodes.query") ||
        Feature == TEXT("overlays.modal") ||
        Feature == TEXT("render.filters") ||
        Feature == TEXT("render.layers") ||
        Feature == TEXT("render.shaders") ||
        Feature == TEXT("render.transform2d") ||
        Feature == TEXT("render.transform3d") ||
        Feature == TEXT("render.ui-material");
}

inline bool RmlUiProfileHasFeature(const FString& Profile, const FString& Feature)
{
    if (Profile == TEXT("dx11-compat"))
        return Feature == TEXT("css.core") ||
        Feature == TEXT("css.grid") ||
        Feature == TEXT("css.motion") ||
        Feature == TEXT("css.variables") ||
        Feature == TEXT("events.extended") ||
        Feature == TEXT("input.ime") ||
        Feature == TEXT("layout.measure") ||
        Feature == TEXT("nodes.query") ||
        Feature == TEXT("overlays.modal") ||
        Feature == TEXT("render.filters") ||
        Feature == TEXT("render.layers") ||
        Feature == TEXT("render.shaders") ||
        Feature == TEXT("render.transform2d") ||
        Feature == TEXT("render.transform3d");
    if (Profile == TEXT("slate-rhi"))
        return Feature == TEXT("css.core") ||
        Feature == TEXT("css.grid") ||
        Feature == TEXT("css.motion") ||
        Feature == TEXT("css.variables") ||
        Feature == TEXT("events.extended") ||
        Feature == TEXT("input.ime") ||
        Feature == TEXT("layout.measure") ||
        Feature == TEXT("nodes.query") ||
        Feature == TEXT("overlays.modal") ||
        Feature == TEXT("render.transform2d") ||
        Feature == TEXT("render.ui-material");
    return false;
}
